<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
     $config['protocol'] = 'smtp';
     $config['smtp_host'] = 'email-smtp.us-west-2.amazonaws.com';
     $config['smtp_port'] = '587';
     $config['smtp_user'] = 'AKIAJKKFD3JWWQK3SQIQ';
     $config['smtp_pass'] = 'AvcS+4fOuHyqFxp7UjgUDw7g1dysls1xAJV9NvT3xjHe';
     $config['mailtype'] = 'html';
     $config['charset'] = 'iso-8859-1';
     $config['wordwrap'] = TRUE;
     $config['newline'] = "\r\n";
     $config['crlf'] = "\r\n";
     $config['smtp_crypto']="tls";
